// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBookSubscription.Catalog.Data;

namespace OnlineBookSubscription.Catalog.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211019130717_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineBookSubscription.Catalog.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Microsoft",
                            Isbn = "10001",
                            Price = 150.0,
                            Thumbnail = "Ad.png",
                            Title = "Azure"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Bob Jane",
                            Isbn = "10002",
                            Price = 250.0,
                            Thumbnail = "cg.png",
                            Title = "Computer Graphics"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Martin",
                            Isbn = "10003",
                            Price = 150.0,
                            Thumbnail = "csharp.png",
                            Title = "C Sharp"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Peter",
                            Isbn = "10004",
                            Price = 120.0,
                            Thumbnail = "java.png",
                            Title = "Java"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Microsoft",
                            Isbn = "10005",
                            Price = 180.0,
                            Thumbnail = "ml.png",
                            Title = "Machine learning"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Carlos",
                            Isbn = "10006",
                            Price = 220.0,
                            Thumbnail = "python.png",
                            Title = "Python"
                        });
                });

            modelBuilder.Entity("OnlineBookSubscription.Catalog.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
